"""Build the typeset paper in Documentation/.

Two steps. First the factor registry is dumped from the database into a LaTeX
table, so the appendix cannot drift away from the panel it documents; if the
database is unreachable the existing table is kept and a warning is printed,
because a paper that builds without a database is more useful than one that does
not build at all. Then pdflatex runs twice — once to lay the document out, once
more to resolve the table of contents and the cross-references.

    python -m scripts.build_paper
"""
from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parents[1] / "Documentation"
MAIN = "factor-model-paper"
TABLE = DOCS / "registry-table.tex"


def _tex(s: str) -> str:
    """Escape the characters LaTeX treats as markup. Identifiers carry underscores."""
    for old, new in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"),
                     ("$", r"\$"), ("#", r"\#"), ("_", r"\_"), ("{", r"\{"),
                     ("}", r"\}"), ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")):
        s = s.replace(old, new)
    return s


def write_registry_table() -> bool:
    """Dump ref_factor as a longtable. Returns False if the database was unreachable."""
    try:
        from backend.pipeline.dbsync import connect
    except Exception as exc:                                  # pragma: no cover
        print(f"  ! cannot import the database layer: {exc}")
        return False

    try:
        with connect() as conn, conn.cursor() as cur:
            cur.execute(
                """
                SELECT f.factor_id, b.name, f.hierarchy_level,
                       array_to_string(f.orthogonalize_against, ', ')
                FROM ref_factor f
                JOIN ref_factor_block b ON b.block_id = f.block_id
                WHERE f.is_active
                ORDER BY b.sort_order, f.hierarchy_level, f.factor_id
                """
            )
            rows = cur.fetchall()
    except Exception as exc:
        print(f"  ! database unreachable, keeping the existing table: "
              f"{str(exc).splitlines()[0][:80]}")
        return False

    out = [
        "% Generated by scripts/build_paper.py — do not edit by hand.",
        r"\begingroup\small",
        r"\setlength{\LTleft}{0pt}\setlength{\LTright}{\fill}",
        r"\begin{longtable}{@{}llc>{\raggedright\arraybackslash}p{0.40\textwidth}@{}}",
        r"\toprule",
        r"\textbf{Factor} & \textbf{Block} & \textbf{Level} & "
        r"\textbf{Residualised against} \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"\textbf{Factor} & \textbf{Block} & \textbf{Level} & "
        r"\textbf{Residualised against} \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endfoot",
    ]

    block_seen = None
    for factor_id, block, level, targets in rows:
        if block_seen is not None and block != block_seen:
            out.append(r"\addlinespace")
        block_seen = block
        against = _tex(targets) if targets else r"\textit{--- used raw}"
        if targets:
            against = r"\texttt{\footnotesize " + against.replace(", ", r"}, \texttt{\footnotesize ") + "}"
        out.append(
            rf"\texttt{{\footnotesize {_tex(factor_id)}}} & {_tex(block)} & "
            rf"{level} & {against} \\"
        )

    out += [r"\end{longtable}", r"\endgroup", ""]
    TABLE.write_text("\n".join(out), encoding="utf-8")
    print(f"  wrote {TABLE.name}: {len(rows)} factors")
    return True


def run_latex() -> int:
    exe = shutil.which("pdflatex")
    if not exe:
        print("! pdflatex not found on PATH — install MiKTeX or TeX Live")
        return 1

    for pass_no in (1, 2):
        proc = subprocess.run(
            [exe, "-interaction=nonstopmode", "-halt-on-error",
             "--enable-installer", f"{MAIN}.tex"],
            cwd=DOCS, capture_output=True, text=True, errors="replace",
        )
        if proc.returncode != 0:
            # The log is far more useful than the console tail; point at both.
            tail = [ln for ln in proc.stdout.splitlines() if ln.startswith("!")]
            print(f"! pdflatex failed on pass {pass_no}")
            print("\n".join(tail[-12:]) or proc.stdout[-1500:])
            print(f"  full log: {DOCS / (MAIN + '.log')}")
            return proc.returncode
        print(f"  pass {pass_no} ok")

    for junk in ("aux", "log", "out", "toc"):
        (DOCS / f"{MAIN}.{junk}").unlink(missing_ok=True)

    pdf = DOCS / f"{MAIN}.pdf"
    print(f"  {pdf.relative_to(DOCS.parent)}: {pdf.stat().st_size / 1024:.0f} kB")
    return 0


def main() -> int:
    print("registry table")
    write_registry_table()
    print("pdflatex")
    return run_latex()


if __name__ == "__main__":
    sys.exit(main())
